"""add_billetera_tarjeta_to_suscripciones

Revision ID: 75381af94d37
Revises: 412538730c36
Create Date: 2026-05-08 17:00:05.326292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75381af94d37'
down_revision: Union[str, Sequence[str], None] = '412538730c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suscripciones', sa.Column('billetera_id', sa.UUID(), nullable=True))
    op.add_column('suscripciones', sa.Column('tarjeta_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'suscripciones', 'billeteras', ['billetera_id'], ['id'])
    op.create_foreign_key(None, 'suscripciones', 'tarjetas_credito', ['tarjeta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suscripciones', type_='foreignkey')
    op.drop_constraint(None, 'suscripciones', type_='foreignkey')
    op.drop_column('suscripciones', 'tarjeta_id')
    op.drop_column('suscripciones', 'billetera_id')
    # ### end Alembic commands ###
